"""Переименовали столбец

Revision ID: 7905ee71151c
Revises: eb1863caa2bd
Create Date: 2023-04-07 18:49:12.467347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7905ee71151c'
down_revision = 'eb1863caa2bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('jobs', sa.Column('is_started2', sa.Boolean(), nullable=True))
    # op.drop_column('jobs', 'is_started')
    op.alter_column('jobs', 'is_started', new_column_name='is_started2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('jobs', sa.Column('is_started', sa.BOOLEAN(), nullable=True))
    # op.drop_column('jobs', 'is_started2')
    op.alter_column('jobs', 'is_started2', new_column_name='is_started')
    # ### end Alembic commands ###
